// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBwWc7i2ITe7OlhDNo_DUMxgAi6puPuyl8',
    appId: '1:771962223357:web:d4574dc3946bded9761c94',
    messagingSenderId: '771962223357',
    projectId: 'african-scene',
    authDomain: 'african-scene.firebaseapp.com',
    storageBucket: 'african-scene.firebasestorage.app',
    measurementId: 'G-B0BRCFVHC0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDCzYlLNWg1Sh9Ra10aeJDuBZymzJQWp2Q',
    appId: '1:771962223357:android:d0f75d75a24f0ede761c94',
    messagingSenderId: '771962223357',
    projectId: 'african-scene',
    storageBucket: 'african-scene.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDkYtm9rJs8pJfk0tLK4vSKfjvz25GsHHo',
    appId: '1:771962223357:ios:1ea46386c2c2b35c761c94',
    messagingSenderId: '771962223357',
    projectId: 'african-scene',
    storageBucket: 'african-scene.firebasestorage.app',
    iosBundleId: 'com.example.africanscene',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDkYtm9rJs8pJfk0tLK4vSKfjvz25GsHHo',
    appId: '1:771962223357:ios:1ea46386c2c2b35c761c94',
    messagingSenderId: '771962223357',
    projectId: 'african-scene',
    storageBucket: 'african-scene.firebasestorage.app',
    iosBundleId: 'com.example.africanscene',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBwWc7i2ITe7OlhDNo_DUMxgAi6puPuyl8',
    appId: '1:771962223357:web:b57a6874f3c32452761c94',
    messagingSenderId: '771962223357',
    projectId: 'african-scene',
    authDomain: 'african-scene.firebaseapp.com',
    storageBucket: 'african-scene.firebasestorage.app',
    measurementId: 'G-P19KHPV16T',
  );
}
